# Numpy Array

In [4]:
import numpy as np

In [5]:
np.array([5,9,13])

array([ 5,  9, 13])

In [6]:
type([5,9,13])

list

In [7]:
a = [1,2]

np.array(a)

array([1, 2])

In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a.shape

(3, 3)

In [10]:
a.ndim

2

In [11]:
lst = list(range(1,10,2))
lst

[1, 3, 5, 7, 9]

In [12]:
lst = list(range(1,10..5,2.5))
lst

SyntaxError: invalid syntax (<ipython-input-12-fcf2579ab4f5>, line 1)

In [13]:
#use arange

In [14]:
lst = np.arange(1,10.5,2.5)
lst

array([1. , 3.5, 6. , 8.5])

# linspace

In [15]:
#linspace  -  difference of number beetween range
lst = np.linspace(10,40,5,)  # difference 7.5
lst

array([10. , 17.5, 25. , 32.5, 40. ])

In [16]:
lst = np.linspace(10,40,4,retstep=True) # difference 10
lst

(array([10., 20., 30., 40.]), 10.0)

lst = np.arange(1,10.5,2.5)
lst

# Matrix creation

In [17]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [18]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
print(2*np.ones((4,5)))

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.linspace(2,3,4,endpoint=False)

array([2.  , 2.25, 2.5 , 2.75])

In [22]:
np.linspace(2,3,4,endpoint=True)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [23]:
np.linspace(2,3,4,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [24]:
x = np.arange(20).reshape(4,5) # reshape value multiplies then = to arange value 
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Random Number generation

In [25]:
#rand -genreate for random numbers
#randn - use for negatie numbers
#randint - use for genreate int number 

In [26]:
print(np.random.rand(5,6))

[[0.71762866 0.37913442 0.16568857 0.7737457  0.68158153 0.49139005]
 [0.48290928 0.14098839 0.57098042 0.44233928 0.56943896 0.35036504]
 [0.77358001 0.9268498  0.6548173  0.90259833 0.48249924 0.86722293]
 [0.5050844  0.27471926 0.18078588 0.27492185 0.524853   0.63643093]
 [0.51430432 0.73194625 0.55700152 0.66022189 0.88003908 0.892204  ]]


In [27]:
print(np.random.randn(5,6))

[[-5.97459690e-01  3.21592904e-01  1.07659644e+00  1.24262818e+00
  -1.90718446e-01 -1.59032817e+00]
 [ 9.91582297e-03  1.16703222e+00 -1.52872198e+00  2.14902499e+00
  -1.70253688e-01 -5.20781277e-01]
 [ 6.98870483e-01 -1.20814101e-03  7.36918422e-02 -1.41496765e+00
  -1.25588943e+00  8.58862518e-01]
 [-1.69100622e+00 -1.43329260e+00  1.84855873e-01 -1.73406290e+00
   1.51685010e+00 -1.11214090e+00]
 [ 8.71070073e-01 -1.89765796e+00  9.24418812e-01 -5.91573837e-02
   1.80560453e+00 -5.32897933e-01]]


In [28]:
print(np.random.randint(1,10,10))

[7 6 3 4 9 1 2 4 4 7]


In [29]:
print(np.random.randint(1,10,(2,5)))

[[2 7 5 2 4]
 [7 7 8 7 9]]


In [30]:
print(np.random.randint(1,10,(5,6)))# np.random.randint( number between (row,columns))

[[1 7 9 3 8 4]
 [9 5 2 8 5 2]
 [4 7 6 1 2 2]
 [6 1 1 8 7 2]
 [9 8 4 5 8 3]]


# Reshaping

In [31]:
import numpy as np

In [32]:
from numpy.random import randint as ri

In [33]:
ri(1,99,(5,5))

array([[38, 18, 66, 14, 40],
       [88, 29, 15, 37, 85],
       [29, 78, 66, 50, 50],
       [ 2, 58, 56, 16, 73],
       [45, 92, 28, 86, 96]])

In [34]:
def random(val1,val2,val3):
    p = np.random.randint(val1,val2,val3)
    print(p)

In [35]:
p = random(1,99,(2,3,5))
p

[[[43 49 91 65  6]
  [ 5 55 78 39 18]
  [79 59 20 62 81]]

 [[65  7 36 41 60]
  [30 22 33 44 52]
  [31 88  9 57 36]]]


In [36]:
a = ri(1,99,30)

In [37]:
b = a.reshape(2,3,5)
b

array([[[ 5, 16, 94, 58, 95],
        [73, 78, 26, 77, 92],
        [71, 35, 82, 23, 18]],

       [[ 9, 73, 91, 51, 92],
        [ 5, 46, 54, 19, 14],
        [49, 86, 29, 54, 84]]])

In [38]:
c = ri(1,99,(5,6))

In [39]:
print(f'print a look like this \n{a}')
print(f'\nprint b look like this \n \n{b}')
print(f'\nprint c look like this \n \n{c}')

print a look like this 
[ 5 16 94 58 95 73 78 26 77 92 71 35 82 23 18  9 73 91 51 92  5 46 54 19
 14 49 86 29 54 84]

print b look like this 
 
[[[ 5 16 94 58 95]
  [73 78 26 77 92]
  [71 35 82 23 18]]

 [[ 9 73 91 51 92]
  [ 5 46 54 19 14]
  [49 86 29 54 84]]]

print c look like this 
 
[[69  2 86 34  9 57]
 [62 71 38 88 77  3]
 [73 28 90 66 59 89]
 [82 37 81 64 63 70]
 [83 39 95  3 52 84]]


In [40]:
a= ri(1,50,10)
print(a)

[39  3 38  8 24 20 30 31 24 31]


In [41]:
print(np.sort(a,kind ='quicksort'))
print(a.max())

[ 3  8 20 24 24 30 31 31 38 39]
39


In [42]:

a= ri(1,10,(2,3,3))
print(a)

[[[6 7 7]
  [9 8 5]
  [4 3 8]]

 [[7 9 8]
  [3 3 1]
  [8 5 2]]]


In [43]:
print(np.sort(a,kind='quicksort'))

[[[6 7 7]
  [5 8 9]
  [3 4 8]]

 [[7 8 9]
  [1 3 3]
  [2 5 8]]]


# indexing and slicing

In [44]:
a = ri(10,50,20)
print(a)
print(a[1:5])


[17 10 23 31 31 12 29 33 19 38 26 35 29 22 27 33 27 12 48 16]
[10 23 31 31]


In [45]:
print(a[:5])


[17 10 23 31 31]


In [46]:
print(a[1:15:3])


[10 31 33 26 22]


In [47]:
print(a[::2])

[17 23 31 29 19 26 29 27 27 48]


In [48]:
print(a[10::-2])

[26 19 29 31 23 17]


In [49]:
b = ri(10,50,(3,3))
print(b)

[[45 11 35]
 [28 17 24]
 [47 43 29]]


In [50]:
print(b[1][2]) # ext one data to array

24


In [51]:
print(b[2]) #ext.. row data

[47 43 29]


In [52]:
print(b[1:,2:])

[[24]
 [29]]


In [53]:
print(b[1:,:])

[[28 17 24]
 [47 43 29]]


In [54]:
print(b[1:2,1:2])

[[17]]


# Subseting

In [55]:
mat = np.array(ri(10,100,15)).reshape(3,5)

print(mat)

[[75 17 24 25 57]
 [16 13 66 87 62]
 [95 78 95 69 97]]


In [56]:
print(mat[mat>50])

[75 57 66 87 62 95 78 95 69 97]


In [57]:
p = np.arange(1,41).reshape(5,8)

In [58]:
print(p)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]]


In [59]:
p[0,0] = 1000
print(p)

[[1000    2    3    4    5    6    7    8]
 [   9   10   11   12   13   14   15   16]
 [  17   18   19   20   21   22   23   24]
 [  25   26   27   28   29   30   31   32]
 [  33   34   35   36   37   38   39   40]]


# ____


In [61]:
a = np.zeros((3,3))
a[0,1] = 200
print(a)

[[  0. 200.   0.]
 [  0.   0.   0.]
 [  0.   0.   0.]]


In [62]:
b1 = np.array([[1,0,2]])
b1

array([[1, 0, 2]])

In [63]:
new = a +  b1
print(new)

[[  1. 200.   2.]
 [  1.   0.   2.]
 [  1.   0.   2.]]


# Array Math

In [64]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

print(mat1)
print(f'\n{mat2}')

[[4 9 2]
 [8 6 2]
 [8 8 6]]

[[8 8 3]
 [5 8 8]
 [1 6 4]]


In [65]:
np.sqrt(mat1)

array([[2.        , 3.        , 1.41421356],
       [2.82842712, 2.44948974, 1.41421356],
       [2.82842712, 2.82842712, 2.44948974]])

In [66]:
np.exp(mat1)

array([[5.45981500e+01, 8.10308393e+03, 7.38905610e+00],
       [2.98095799e+03, 4.03428793e+02, 7.38905610e+00],
       [2.98095799e+03, 2.98095799e+03, 4.03428793e+02]])

In [67]:
np.log(mat1)

array([[1.38629436, 2.19722458, 0.69314718],
       [2.07944154, 1.79175947, 0.69314718],
       [2.07944154, 2.07944154, 1.79175947]])

In [66]:
np.log10(53)

1.724275869600789

In [67]:
np.square(10)

100

# Broadcasting

In [71]:
#add row
start = np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [72]:
add_row=np.array([1,0,2])
print(add_row)

[1 0 2]


In [73]:
y =start+add_row
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [81]:
add_cols = np.array([[0,1,2,3]])
add_cols =  add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [83]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [86]:
add_row=np.array([[1,0,2]])
n = add_row.T
n

array([[1],
       [0],
       [2]])

In [87]:
print(start+n)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]
